catering:
  # 开发者应该设置成自己的wx相关信息
  wx:
    app-id: wxbb237ea48637ee39
    app-secret: 374ea3798ccaba23c40addf8f0b2aceb
    mch-id: 1530966771
    mch-key: chen20051107lin19830218yang74818
    notify-url: https://test.dtsshop.com/demo/order/dtsNotify
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx

 #通知相关配置
  notify:
    mail:
      # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
      enable: true
      host: smtp.aliyun.com
      username: dtsshop@aliyun.com
      password: xxx
      sendfrom: xxx@aliyun.com
      sendto: xxx@qq.com

    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: true
      appid: 123
      appkey: xxx
      template:
      - name: paySucceed
        templateId: 112233
      - name: captcha
        templateId: 112233
      - name: ship
        templateId: 112233
      - name: refund
        templateId: 112233

    # 微信模版通知配置
    # 微信模版用于通知客户或者运营者，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    wx:
      enable: true
      template:
      - name: paySucceed
        templateId: sirUcgTAIQfoIxxxxxx
      - name: captcha
        templateId: OfBkXh7UILpsDkcxxxxxx
      - name: ship
        templateId: dqTuWzrmL_wwK-SJsxxxxxx
      - name: applyRefund
        templateId: lzPHltMpUOiBol7i2Yxxxxxx
      - name: refund
        templateId: NDy6EpPuu2C9NMUxxxxxx

  # 快鸟物流查询配置
  express:
    enable: true
    appId: "xxxxxx"
    appKey: "xxxxxx"
    vendors:
    - code: "HTKY"
      name: "百世快递"
    - code: "YZBK"
      name: "邮政国内标快"
    - code: "ZTO"
      name: "中通快递"
    - code: "YTO"
      name: "圆通速递"
    - code: "YD"
      name: "韵达速递"
    - code: "YZPY"
      name: "邮政快递包裹"
    - code: "EMS"
      name: "EMS"
    - code: "DBL"
      name: "德邦快递"
    - code: "FAST"
      name: "快捷快递"
    - code: "ZJS"
      name: "宅急送"
    - code: "TNT"
      name: "TNT快递"
    - code: "UPS"
      name: "UPS"
    - code: "DHL"
      name: "DHL"
    - code: "FEDEX"
      name: "FEDEX联邦(国内件)"
    - code: "FEDEX_GJ"
      name: "FEDEX联邦(国际件)"

  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: aliyun
    # 本地对象存储配置信息
    local:
      storagePath: catering/storage/
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://localhost:8070/wx/storage/fetch/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: http://oss-cn-shenzhen.aliyuncs.com
      accessKeyId: LTAI4FpiF18xnmDnKggv4wDf
      accessKeySecret: ADGeUIbMFUnLtgrkYbrbJ2O6VezNLO
      bucketName: dev-my-common
      domain: http://dev-my-common.meiy520.com/
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: 111111
      secretKey: xxxxxx
      region: xxxxxx
      bucketName: dts
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://dtsshop.wx.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: dts

pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      filter:
        stat:
          log-slow-sql: true
          merge-sql: false
          slow-sql-millis: 1000
      initial-size: 10
      max-active: 100
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 10
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filters:  stat,wall
      url: jdbc:mysql://192.168.98.81:3306/catering_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 163@.com
  main:
    allow-bean-definition-overriding: true


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.meiyuan.catering.goods.entity,com.meiyuan.catering.merchant.entity,com.meiyuan.catering.marketing.entity,com.meiyuan.catering.order.entity,com.meiyuan.catering.user.entity
  type-handlers-package: com.meiyuan.catering.core.mybatis
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER_STR
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      database: 12
      host: 192.168.98.81
      password: Meiyuan123
      port: 6379

#消息中心
message:
  host: http://msg-dev.meiy520.com
  loginUrl: ${message.host}/msg/api/openApiFacade/login
  username: admin3
  password: 123456
  sendMsgUrl: ${message.host}/msg/api/openApiFacade/synSendMsg
  aliShortMsgAppId: 10121

psssword:
  encrypt:
    key: 1234567890123456
    iv: 1234567890123456 # 16位数字

# ali敏感词过滤相关配置
baidu:
  appId: 18438785
  apiKey: ZlY2xvskwzKkFHNgWz3tCBaI
  secretKey: TT6rZ2TN0xLhRaQHC5z2OVE1gaSifh8M
  connectionTimeout: 2000
  socketTimeout: 60000