spring:
  main:
    allow-bean-definition-overriding: true
app:
  id: uat-xs-front-wx-api
apollo:
  meta: http://192.168.98.74:18080
  bootstrap:
    enabled: true
    namespaces: application,uat-xs-catering.common.config