spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 80MB
      #location: /tmp/tomcat_upload


server:
  port: 8074
  servlet:
    context-path: /wx

##logger配置
logging:
  config: classpath:logback-spring.xml
