spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 80MB
      #location: /tmp/tomcat_upload

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.qiguliuxing.dts.admin:  DEBUG
    com.qiguliuxing.dts:  DEBUG
