spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: common


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.meiyuan.catering.goods.entity,com.meiyuan.catering.merchant.entity,com.meiyuan.catering.marketing.entity,com.meiyuan.catering.order.entity,com.meiyuan.catering.user.entity
  type-handlers-package: com.meiyuan.catering.core.mybatis
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#商品商户id
goods:
  merchant:
    id: 1

psssword:
  encrypt:
    key: 1234567890123456
    iv: 1234567890123456 # 16位数字
app-version:
  forced-update: true
  remind-update: true
  version-num: 1.3.0
  remind_word: 您当前的版本太低，需要升级到最新版本。

swagger:
  enabled: true
  docket:
    goods:
      title: 商品
      base-package: com.meiyuan.catering.merchant.api.goods
    marketing:
      title: 营销
      base-package: com.meiyuan.catering.merchant.api.marketing
    merchant:
      title: 商户
      base-package: com.meiyuan.catering.merchant.api.merchant
    order:
      title: 订单
      base-package: com.meiyuan.catering.merchant.api.order
    storage:
      title: 文件上传
      base-package: com.meiyuan.catering.merchant.api.storage
    common:
      title: 文字图片过滤
      base-package: com.meiyuan.catering.merchant.api.common
    notify:
      title: 文字图片过滤
      base-package: com.meiyuan.catering.merchant.api.notify
  authorization:
    key-name: X-Catering-Token

